### ISSUE TITLE
(minor) License & copyright?

### ISSUE THREAD

**Issue by jimvanderveen** [CDLUC3/dashv2#2]
What license are you using on this project?
Copyright by the Regents?

**Comment by mxsstrong** [comment]
We will be using the the MIT license copyrighted by the Regents.

**Comment by dmolesUC3** [comment]
License added some time ago: https://github.com/CDLUC3/dashv2/commit/2d579ec5f5e6c8914650566e91663d131f8ca488#diff-37854d19817c792316d481f5beb93cc7
